[package]
name = "redis-ctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"]}
redis = {version = "0.23.3", features = ["aio", "tokio-comp", "connection-manager"]}
serde = {version = "1.0.188", features = ["derive"]}
serde_json = {version = "1.0.105", features = ["std"]}
