name: Rust

on:
  push:
    branches: [ "main" ]
    paths-ignore: "**.md"

  pull_request:
    branches: [ "main" ]
    paths-ignore: "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build dnsblrsd
      run: cargo build --manifest-path ./dnsblrsd/Cargo.toml --verbose --release

    - name: Build redis-ctl
      run: cargo build --manifest-path ./redis-ctl/Cargo.toml --verbose --release
